### ISSUE TITLE
Not working on Ubuntu 14.04

### ISSUE THREAD

**Issue by corsairdnb** [avocode/avocode#315]
Avocode fails just after opening. However UI is clickable, but project manager eternally syncing and never loads.

-----

```
TypeError: object is not a function
    at t.<anonymous> (/home/dmitry/Downloads/Avocode/resources/app.asar/node_modules/@avocode/core/lib/avocode.js:1:26467)
    at t.EventEmitter.emit (/home/dmitry/Downloads/Avocode/resources/app.asar/node_modules/@avocode/core/node_modules/eventemitter2/lib/eventemitter2.js:339:22)
    at e._onUserData (/home/dmitry/Downloads/Avocode/resources/app.asar/node_modules/@avocode/core/lib/user.js:1:8253)
    at /home/dmitry/Downloads/Avocode/resources/app.asar/node_modules/@avocode/core/lib/user.js:1:342
    at Request._callback (/home/dmitry/Downloads/Avocode/resources/app.asar/node_modules/@avocode/core/lib/api.js:1:2348)
    at Request.self.callback (/home/dmitry/Downloads/Avocode/resources/app.asar/node_modules/@avocode/core/node_modules/request/request.js:197:22)
    at emitTwo (events.js:92:20)
    at Request.emit (events.js:169:7)
    at Request.<anonymous> (/home/dmitry/Downloads/Avocode/resources/app.asar/node_modules/@avocode/core/node_modules/request/request.js:1050:14)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:166:7)
    at IncomingMessage.<anonymous> (/home/dmitry/Downloads/Avocode/resources/app.asar/node_modules/@avocode/core/node_modules/request/request.js:996:12)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:163:7)
    at _stream_readable.js:891:16
    at process._tickCallback (node.js:357:13)
```
![avocode](https://cloud.githubusercontent.com/assets/4211598/8287293/878f41ae-1917-11e5-832e-817507e81473.jpg)

**Comment by corsairdnb** [comment]
Problem is solved in v0.22.3
